name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libsdl2-dev libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev

    - name: Install Raylib
      run: |
        git clone https://github.com/raysan5/raylib.git
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install

    - name: Build project
      run: |
        cd build
        make clean
        make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jingle_bells_synth
        path: build/jingle_bells_synth
